/// MuSheet Serverpod Client Library
/// 
/// This library provides the client-side interface for connecting
/// Flutter apps to the MuSheet Serverpod backend.
/// 
/// Usage:
/// ```dart
/// import 'package:musheet_client/musheet_client.dart';
/// 
/// final client = Client('http://localhost:8080/')
///   ..connectivityMonitor = FlutterConnectivityMonitor();
/// 
/// // Login
/// final result = await client.auth.login('username', 'password');
/// 
/// // Get scores
/// final scores = await client.score.getScores();
/// ```
library;

// Export generated protocol and client
// These will be generated by `serverpod generate`
export 'src/protocol/protocol.dart';
export 'src/protocol/client.dart';